### ISSUE TITLE
English manuals

### ISSUE THREAD

**Issue by andre-cunha** [jgilfillan/Niz-Plum-84EC-S-Pro-Ble-Non-RGB-manual#5]
Hi!

Just want to point that niz made english manuals free available at their website: https://www.nizkeyboard.com/download/

For instance, 75 rgb manual can be found here: https://www.dropbox.com/sh/rfmf9r95frmbbtg/AABPNnMLTKn_zlRbHFe4mxTWa?dl=0&preview=KB75+User+Manual.doc

**Comment by jgilfillan** [comment]
Thanks, but I couldn't find a manual for my keyboard, the 84EC Pro Ble Non-RGB on the website.
